# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: output/BurnScars
      name: burn_scars_1e-5
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 40

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: output/BurnScars

data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 8
    constant_scale: 10000  # Scale 0-1 to 0-10000 (HLS pre-training data)
    dataset_bands:  # Dataset bands
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands: # Model input bands
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_data_root: data/HLSBurnScars/training
    val_data_root: data/HLSBurnScars/validation
    test_data_root: data/HLSBurnScars/validation
    img_grep: "*_merged.tif"
    label_grep: "*.mask.tif"
    means:
      - 775.229
      - 1080.992
      - 1228.585
      - 2497.202
      - 2204.213
      - 1610.832
    stds:
      - 1281.526
      - 1270.029
      - 1399.480
      - 1368.344
      - 1291.676
      - 1154.505
    num_classes: 2
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: ToTensorV2
    no_data_replace: 0
    no_label_replace: -1

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: FCNDecoder
      pretrained: true
      backbone: prithvi_vit_100
      decoder_channels: 256
      in_channels: 6
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 2
      head_dropout: 0.1
      decoder_num_convs: 4
      head_channel_list:
        - 256
    loss: dice
    plot_on_val: 10
    ignore_index: -1
    class_weights:
      - 0.9 # 11% burn scars
      - 0.1 # 88% not burned
    freeze_backbone: false
    freeze_decoder: false
    model_factory: PrithviModelFactory
    class_names:
      - Burned
      - Not burned
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
